services:
  lightrag-base:
    profiles: ["_template"]
    image: chrpue/lightrag-service:1.4.6

    depends_on:
      lightrag-postgres: { condition: service_healthy }
      lightrag-neo4j: { condition: service_healthy }

    restart: unless-stopped

    env_file: [.env]

    extra_hosts: ["host.docker.internal:host-gateway"]

    environment:
      - PYTHONUNBUFFERED=1

    entrypoint: ["lightrag-gunicorn"]

    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./.env:/app/.env:ro

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9621 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

    networks:
      - lightrag-network
