services:
  lightrag-postgres:
    image: shangor/postgres-for-rag:v1.0
    container_name: lightrag-postgres
    restart: unless-stopped
    ports: ["25432:5432"]
    env_file: [.env]
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - lightrag_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag"]
      interval: 10s
      timeout: 5s
      retries: 5

  lightrag-neo4j:
    image: neo4j:community-ubi9
    container_name: lightrag-neo4j
    restart: unless-stopped
    ports:
      - "17474:7474"
      - "17687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_apoc_export_file_enabled: "true"
    volumes:
      - lightrag_neo4j_data:/data
    healthcheck:
      test:
        - CMD
        - bash
        - -lc
        - >
          /var/lib/neo4j/bin/cypher-shell -a bolt://localhost:7687
          -u neo4j -p "$NEO4J_PASSWORD" --encryption=false 'RETURN 1' >/dev/null
      interval: 15s
      timeout: 5s
      start_period: 120s
      retries: 10

  # ---------------- LightRAG（三实例；仅各自设置 WORKSPACE） ----------------
  lightrag-strategy:
    image: ghcr.io/hkuds/lightrag:1.4.6
    container_name: lightrag-strategy
    depends_on:
      lightrag-postgres: { condition: service_healthy }
      lightrag-neo4j: { condition: service_healthy }
    restart: unless-stopped
    ports: ["19621:9621"]
    env_file: [.env]
    environment:
      WORKSPACE: strategy
    volumes:
      - lightrag_inputs_strategy:/app/data/inputs
      - lightrag_storage_strategy:/app/data/rag_storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9621/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  lightrag-app:
    image: ghcr.io/hkuds/lightrag:1.4.6
    container_name: lightrag-app
    depends_on:
      lightrag-postgres: { condition: service_healthy }
      lightrag-neo4j: { condition: service_healthy }
    restart: unless-stopped
    ports: ["19622:9621"]
    env_file: [.env]
    environment:
      WORKSPACE: app
    volumes:
      - lightrag_inputs_app:/app/data/inputs
      - lightrag_storage_app:/app/data/rag_storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9621/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  lightrag-gas:
    image: ghcr.io/hkuds/lightrag:1.4.6
    container_name: lightrag-gas
    depends_on:
      lightrag-postgres: { condition: service_healthy }
      lightrag-neo4j: { condition: service_healthy }
    restart: unless-stopped
    ports: ["19623:9621"]
    env_file: [.env]
    environment:
      WORKSPACE: gas
    volumes:
      - lightrag_inputs_gas:/app/data/inputs
      - lightrag_storage_gas:/app/data/rag_storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9621/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  lightrag_pg_data:
    external: true
  lightrag_neo4j_data:
    external: true
  lightrag_inputs_app:
    external: true
  lightrag_inputs_strategy:
    external: true
  lightrag_inputs_gas:
    external: true
  lightrag_storage_app:
    external: true
  lightrag_storage_strategy:
    external: true
  lightrag_storage_gas:
    external: true
